- pipeline.id: places-pipeline
  path.config: "/usr/share/logstash/pipeline/places.conf"
  pipeline.workers: 1
- pipeline.id: posts-pipeline
  path.config: "/usr/share/logstash/pipeline/posts.conf"
- pipeline.id: tags-pipeline
  path.config: "/usr/share/logstash/pipeline/tags.conf"
- pipeline.id: trips-pipeline
  path.config: "/usr/share/logstash/pipeline/trips.conf"
- pipeline.id: users-pipeline
  path.config: "/usr/share/logstash/pipeline/users.conf"